import streamlit as st

translations = {
    "English": {
        "app_title": "VitaNova AI",
        "subtitle": "Intelligent Health & Wellness Assistant",
        "warning": "⚠️ This app is for awareness only. Consult a doctor for medical advice.",

        "modules": "Modules",
        "disease_title": "Disease Risk Detector",
        "mental_title": "Mental Health Check-in",
        "diet_title": "AI Smart Diet Planner",
        "medicine_title": "Medicine Safety Checker",
        "sos_title": "Emergency SOS",
        "hospital_title": "Hospital Finder",
        "habit_title": "Habit Tracker",
        "dashboard_title": "Health Dashboard",
        "workout_title": "Target Workout",
        "chatbot": "Health Chatbot",

        "age": "Age",
        "height": "Height",
        "weight": "Weight",
        "sleep": "Sleep Hours",
        "exercise": "Exercise Level",
        "smoking": "Smoking",
        "alcohol": "Alcohol",
        "sugar": "High Sugar Intake",
        "family": "Family History",
        "bp": "High Blood Pressure",

        "low": "Low",
        "moderate": "Moderate",
        "high": "High",
        "yes": "Yes",
        "no": "No",

        "check": "Check",
        "check_risk": "Check Risk",
        "save": "Save",
        "send": "Send",
        "generate": "Generate",
        "find": "Find",
        "add": "Add",

        "name": "Name",
        "location": "Location",
        "guardian_email": "Guardian Email",
        "city": "City",

        "goal": "Goal",
        "diet_type": "Diet Preference",
        "activity": "Activity Level",
        "region": "Region",
        "health_condition": "Health Condition",

        "medicine_name": "Enter Medicine Names",
        "dosage": "Dosage",
        "morning": "Morning",
        "afternoon": "Afternoon",
        "night": "Night",
        "interaction": "Interaction Results",
        "no_interaction": "No known interaction found. This does not guarantee full safety.",

        "bmi": "BMI",
        "risk_score": "Risk Score",
        "risk_level": "Risk Level",
        "risk_factors": "Risk Factors",

        "select_habits": "Select completed habits",
        "add_habit": "Add Custom Habit",
        "habit_saved": "Habit saved successfully",

        "nearby_hospital": "Nearby hospitals and clinics",
        "open_maps": "Open Google Maps",
        "hospital_info": "Includes hospitals, clinics, and emergency care centers.",
        "care_type": "Care Type",

        "body_part": "Select Body Part",
        "show_exercises": "Show Exercises",
        "arms": "Arms",
        "legs": "Legs",
        "belly": "Belly",
        "chest": "Chest",
        "back": "Back",
        "full_body": "Full Body",
        "eyes": "Eyes",
        "neck": "Neck",

        "type_question": "Type your question in English",
        "voice": "Ask by Voice",
        "start_recording": "Start Recording",
        "stop_recording": "Stop Recording",
        "chat_history": "Chat History",
    },

    "Tamil": {
        "app_title": "விட்டாநோவா AI",
        "subtitle": "அறிவார்ந்த ஆரோக்கிய மற்றும் நல உதவியாளர்",
        "warning": "⚠️ இந்த பயன்பாடு விழிப்புணர்விற்காக மட்டுமே. மருத்துவ ஆலோசனைக்கு மருத்துவரை அணுகவும்.",

        "modules": "அம்சங்கள்",
        "disease_title": "நோய் அபாய கண்டறிதல்",
        "mental_title": "மனநலம் சோதனை",
        "diet_title": "AI உணவு திட்டம்",
        "medicine_title": "மருந்து பாதுகாப்பு சோதனை",
        "sos_title": "அவசர SOS உதவி",
        "hospital_title": "மருத்துவமனை கண்டறிதல்",
        "habit_title": "பழக்க கண்காணிப்பு",
        "dashboard_title": "ஆரோக்கிய டாஷ்போர்டு",
        "workout_title": "இலக்கு உடற்பயிற்சி",
        "chatbot": "ஆரோக்கிய சாட்பாட்",

        "age": "வயது",
        "height": "உயரம்",
        "weight": "எடை",
        "sleep": "தூக்க நேரம்",
        "exercise": "உடற்பயிற்சி நிலை",
        "smoking": "புகைபிடித்தல்",
        "alcohol": "மது அருந்துதல்",
        "sugar": "அதிக சர்க்கரை உட்கொள்ளல்",
        "family": "குடும்ப வரலாறு",
        "bp": "உயர் இரத்த அழுத்தம்",

        "low": "குறைவு",
        "moderate": "மிதமான",
        "high": "அதிகம்",
        "yes": "ஆம்",
        "no": "இல்லை",

        "check": "சரிபார்",
        "check_risk": "அபாயத்தை சரிபார்",
        "save": "சேமி",
        "send": "அனுப்பு",
        "generate": "உருவாக்கு",
        "find": "கண்டறி",
        "add": "சேர்",

        "name": "பெயர்",
        "location": "இடம்",
        "guardian_email": "பாதுகாவலர் மின்னஞ்சல்",
        "city": "நகரம்",

        "goal": "இலக்கு",
        "diet_type": "உணவு விருப்பம்",
        "activity": "செயல்பாட்டு நிலை",
        "region": "பகுதி",
        "health_condition": "உடல்நிலை",

        "medicine_name": "மருந்து பெயர்களை உள்ளிடவும்",
        "dosage": "அளவு",
        "morning": "காலை",
        "afternoon": "மதியம்",
        "night": "இரவு",
        "interaction": "மருந்து தொடர்பு முடிவுகள்",
        "no_interaction": "எந்த மருந்து தொடர்பும் கண்டறியப்படவில்லை. இது முழு பாதுகாப்பை உறுதி செய்யாது.",

        "bmi": "உடல் நிறை குறியீடு",
        "risk_score": "அபாய மதிப்பெண்",
        "risk_level": "அபாய நிலை",
        "risk_factors": "அபாய காரணிகள்",

        "select_habits": "முடித்த பழக்கங்களை தேர்வு செய்யவும்",
        "add_habit": "புதிய பழக்கத்தை சேர்க்கவும்",
        "habit_saved": "பழக்கம் வெற்றிகரமாக சேமிக்கப்பட்டது",

        "nearby_hospital": "அருகிலுள்ள மருத்துவமனைகள் மற்றும் கிளினிக்குகள்",
        "open_maps": "Google Maps திறக்கவும்",
        "hospital_info": "மருத்துவமனைகள், கிளினிக்குகள் மற்றும் அவசர சேவை மையங்கள் அடங்கும்.",
        "care_type": "சிகிச்சை வகை",

        "body_part": "உடல் பகுதியை தேர்வு செய்யவும்",
        "show_exercises": "உடற்பயிற்சிகளை காட்டு",
        "arms": "கைகள்",
        "legs": "கால்கள்",
        "belly": "வயிறு",
        "chest": "மார்பு",
        "back": "முதுகு",
        "full_body": "முழு உடல்",
        "eyes": "கண்கள்",
        "neck": "கழுத்து",

        "type_question": "உங்கள் கேள்வியை ஆங்கிலத்தில் தட்டச்சு செய்யவும்",
        "voice": "குரல் மூலம் கேள்",
        "start_recording": "பதிவு தொடங்கு",
        "stop_recording": "பதிவு நிறுத்து",
        "chat_history": "உரையாடல் வரலாறு",
    },

    "Hindi": {
        "app_title": "विटानोवा AI",
        "subtitle": "बुद्धिमान स्वास्थ्य और वेलनेस सहायक",
        "warning": "⚠️ यह ऐप केवल जागरूकता के लिए है। चिकित्सा सलाह के लिए डॉक्टर से संपर्क करें।",

        "modules": "मॉड्यूल",
        "disease_title": "रोग जोखिम पहचान",
        "mental_title": "मानसिक स्वास्थ्य जांच",
        "diet_title": "AI डाइट प्लानर",
        "medicine_title": "दवा सुरक्षा जांच",
        "sos_title": "आपातकालीन SOS",
        "hospital_title": "अस्पताल खोजक",
        "habit_title": "आदत ट्रैकर",
        "dashboard_title": "स्वास्थ्य डैशबोर्ड",
        "workout_title": "लक्षित व्यायाम",
        "chatbot": "स्वास्थ्य चैटबॉट",

        "age": "उम्र",
        "height": "ऊंचाई",
        "weight": "वजन",
        "sleep": "नींद के घंटे",
        "exercise": "व्यायाम स्तर",
        "smoking": "धूम्रपान",
        "alcohol": "शराब सेवन",
        "sugar": "अधिक चीनी सेवन",
        "family": "पारिवारिक इतिहास",
        "bp": "उच्च रक्तचाप",

        "low": "कम",
        "moderate": "मध्यम",
        "high": "अधिक",
        "yes": "हाँ",
        "no": "नहीं",

        "check": "जांचें",
        "check_risk": "जोखिम जांचें",
        "save": "सेव करें",
        "send": "भेजें",
        "generate": "जनरेट करें",
        "find": "खोजें",
        "add": "जोड़ें",

        "name": "नाम",
        "location": "स्थान",
        "guardian_email": "गार्जियन ईमेल",
        "city": "शहर",

        "goal": "लक्ष्य",
        "diet_type": "डाइट पसंद",
        "activity": "गतिविधि स्तर",
        "region": "क्षेत्र",
        "health_condition": "स्वास्थ्य स्थिति",

        "medicine_name": "दवा के नाम लिखें",
        "dosage": "खुराक",
        "morning": "सुबह",
        "afternoon": "दोपहर",
        "night": "रात",
        "interaction": "दवा इंटरैक्शन परिणाम",
        "no_interaction": "कोई दवा इंटरैक्शन नहीं मिला। यह पूर्ण सुरक्षा की गारंटी नहीं है।",

        "bmi": "BMI",
        "risk_score": "जोखिम स्कोर",
        "risk_level": "जोखिम स्तर",
        "risk_factors": "जोखिम कारण",

        "select_habits": "पूरी की गई आदतें चुनें",
        "add_habit": "नई आदत जोड़ें",
        "habit_saved": "आदत सफलतापूर्वक सेव हुई",

        "nearby_hospital": "पास के अस्पताल और क्लिनिक",
        "open_maps": "Google Maps खोलें",
        "hospital_info": "अस्पताल, क्लिनिक और आपातकालीन सेवा केंद्र शामिल हैं।",
        "care_type": "देखभाल प्रकार",

        "body_part": "शरीर का भाग चुनें",
        "show_exercises": "व्यायाम दिखाएँ",
        "arms": "हाथ",
        "legs": "पैर",
        "belly": "पेट",
        "chest": "छाती",
        "back": "पीठ",
        "full_body": "पूरा शरीर",
        "eyes": "आँखें",
        "neck": "गर्दन",

        "type_question": "अपना प्रश्न अंग्रेज़ी में लिखें",
        "voice": "आवाज़ से पूछें",
        "start_recording": "रिकॉर्डिंग शुरू करें",
        "stop_recording": "रिकॉर्डिंग रोकें",
        "chat_history": "चैट इतिहास",
    }
}

def current_lang():
    return st.session_state.get("lang", "English")

def t(key):
    return translations.get(current_lang(), translations["English"]).get(key, key)